In [2]:
import numpy as np

# **. Dot Product and Matrix Multiplication**

In [3]:
a_vector=np.array([1,2,3])
b_vector=np.array([2,3,4])

dot_product=int(np.dot(a_vector , b_vector))
dot_product

20

In [4]:
c=np.array([1,2])
d=np.array([2,3,4])
# np.dot(c,d) it will give error in this case
c=np.array([1,2])
d=np.array([2,3])
dot_product= int(c@d)
dot_product

8

In [5]:
matrix_1=np.arange(start=1, stop=17 , step=1 , dtype='int64').reshape(4,4)
matrix_2=np.arange(start=1, stop=13 , step=1 , dtype='int64').reshape(4,3)

In [6]:
mat_multiplication = matrix_1@matrix_2
mat_multiplication

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330],
       [334, 392, 450]])

In [7]:
mat_multiplication = np.matmul(matrix_1 , matrix_2)
mat_multiplication

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330],
       [334, 392, 450]])

# **. Determinant , transpose and Inverse**



---

**1. Determinant of the Matrix**

In [8]:
matrix=np.arange(start=1, stop=10 , step=1 , dtype='int64').reshape(3,3)
determinant = np.linalg.det(matrix)
determinant

np.float64(0.0)

In [9]:
print(dir(np.linalg))

['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_linalg', '_umath_linalg', 'cholesky', 'cond', 'cross', 'det', 'diagonal', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matmul', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'multi_dot', 'norm', 'outer', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'svdvals', 'tensordot', 'tensorinv', 'tensorsolve', 'test', 'trace', 'vecdot', 'vector_norm']


In [10]:
mat=np.array([[19,20,30],[12,21,23],[34,56,43]])
determinant = np.linalg.det(mat)
determinant

np.float64(-3254.999999999999)



---

**2. Transpose of the Matrix**

In [11]:
mat=np.array([[19,20,30],[12,21,23],[34,56,43]])
mat

array([[19, 20, 30],
       [12, 21, 23],
       [34, 56, 43]])

In [12]:
mat.T , np.transpose(mat) , mat.transpose() , np.linalg.matrix_transpose(mat)

(array([[19, 12, 34],
        [20, 21, 56],
        [30, 23, 43]]),
 array([[19, 12, 34],
        [20, 21, 56],
        [30, 23, 43]]),
 array([[19, 12, 34],
        [20, 21, 56],
        [30, 23, 43]]),
 array([[19, 12, 34],
        [20, 21, 56],
        [30, 23, 43]]))



---

**3. Inverse of the Matrix**

In [13]:
mat=np.array([[19,20,30],[12,21,23],[34,56,43]])
inverse_mat=np.linalg.inv(mat)
inverse_mat

array([[ 0.11827957, -0.25192012,  0.05222734],
       [-0.08172043,  0.06236559,  0.02365591],
       [ 0.01290323,  0.11797235, -0.04884793]])

# **. System of Linear EQNS**
##### ***In this code, a system of linear equations is being solved using matrix operations in Python with the NumPy library.***

##### ***Breakdown of the Steps***
##### ***Defining Matrices:***

##### ***A 3x3 matrix named A is created from the numbers 1 to 8 and then 10. This matrix represents the coefficients of the variables.***

##### ***A 3x1 matrix (a column vector) named B is created. This matrix represents the constants on the right-hand side of the*** equations.

##### ***Solving the System:***

##### ***The code calculates the inverse of matrix A using np.linalg.inv(A).***

##### ***It then performs a matrix multiplication (@) of the inverse of A with matrix B.***

##### ***This operation, based on the formula x=A −1b, directly solves for the unknown variables. The result is stored in the variable X***



In [14]:
A=np.array([1,2,3,4,5,6,7,8,10]).reshape(3,3)
B=np.array([10,11,12]).reshape(3,1)

In [17]:
X=np.linalg.inv(A)@ B
X

array([[-9.33333333e+00],
       [ 9.66666667e+00],
       [ 2.22044605e-15]])

In [16]:
x=np.linalg.solve(A,B)
x

array([[-9.33333333e+00],
       [ 9.66666667e+00],
       [ 3.55271368e-15]])

# **Eigen Value and Eigen Vector**

In [19]:
A=np.array([[5,4],[1,2]])
EigenValues , EigenVectors=np.linalg.eig(A)

In [20]:
EigenValues , EigenVectors

(array([6., 1.]),
 array([[ 0.9701425 , -0.70710678],
        [ 0.24253563,  0.70710678]]))